accelerator: gpu
precision: 32
devices: 1

dataset_root: /home/aagorodilova_2/PROJECT-Deep_Metric_Learning/CARS196
dataframe_name: df.csv
logs_root: /home/aagorodilova_2/PROJECT-Deep_Metric_Learning/logs/CARS196/

bs_val: 128
num_workers: 20

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224

weights: /home/aagorodilova_2/PROJECT-Deep_Metric_Learning/logs/CARS196/2023-03-28_02-32-42_metric_learning_cars/checkpoints/best.ckpt

model:
  name: vit
  args:
    arch: vits16
    normalise_features: True
    use_multi_scale: False
    weights: ${weights}

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 5]
  map_top_k: [5]
  precision_top_k: [5]
  fmr_vals: [0.01]
  pfc_variance: [0.5, 0.9, 0.99]
  return_only_main_category: False
  visualize_only_main_category: True

hydra:
  searchpath:
   - pkg://oml.configs
