accelerator: gpu
precision: 32
devices: 1

dataset_root: /home/aagorodilova_2/PROJECT-Deep_Metric_Learning/CARS196
dataframe_name: df_no_bboxes.csv

bs_val: 128
num_workers: 20
n_queries: 3

extractor_weights: /home/aagorodilova_2/PROJECT-Deep_Metric_Learning/logs/CARS196/2023-04-16_01-19-44_metric_learning_cars/checkpoints/best.ckpt
postprocessor_weights: /home/aagorodilova_2/PROJECT-Deep_Metric_Learning/logs/CARS196/2023-04-25_16-12-01_postprocessing/checkpoints/best.ckpt

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224

model:
  name: vit
  args:
    arch: vits16
    normalise_features: True
    use_multi_scale: False
    weights: ${extractor_weights}

pairwise_model:
  name: multi_query_attn
  args:
    hidden_dim: 256
    n_query: ${n_queries}
    weights: ${postprocessor_weights}

postprocessor:
  name: multiple_emb
  args:
    top_n: 15
    n_queries: ${n_queries}
    pairwise_model: ${pairwise_model}
    num_workers: ${num_workers}
    batch_size: ${bs_val}
    verbose: True
    use_fp16: True

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 5]
  map_top_k: [5]
  precision_top_k: [5]
  fmr_vals: [0.01]
  pfc_variance: [0.5, 0.9, 0.99]
  return_only_main_category: False
  visualize_only_main_category: True

hydra:
  searchpath:
   - pkg://oml.configs